/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "tertiary": "var(--color-tertiary)",
              "inverse-primary": "var(--color-inverse-primary)",
              "tertiary-container": "var(--color-tertiary-container)",
              "secondary-container": "var(--color-secondary-container)",
              "on-surface-variant": "var(--color-on-surface-variant)",
              "secondary": "var(--color-secondary)",
              "surface-bright": "var(--color-surface-bright)",
              "surface-container-low": "var(--color-surface-container-low)",
              "inverse-on-surface": "var(--color-inverse-on-surface)",
              "surface-container": "var(--color-surface-container)",
              "inverse-surface": "var(--color-inverse-surface)",
              "tertiary-fixed": "#ffdad7",
              "surface-variant": "var(--color-surface-variant)",
              "on-primary-fixed": "#241a00",
              "outline": "var(--color-outline)",
              "on-background": "var(--color-on-background)",
              "surface-container-high": "var(--color-surface-container-high)",
              "error": "var(--color-error)",
              "background": "var(--color-background)",
              "primary-container": "var(--color-primary-container)",
              "on-tertiary-fixed-variant": "#930018",
              "on-secondary-container": "var(--color-on-secondary-container)",
              "error-container": "var(--color-error-container)",
              "surface-container-highest": "var(--color-surface-variant)",
              "surface-tint": "var(--color-primary)",
              "on-primary-fixed-variant": "#584400",
              "tertiary-fixed-dim": "#ffb3af",
              "outline-variant": "var(--color-outline-variant)",
              "on-secondary-fixed": "#00210c",
              "on-secondary": "var(--color-on-secondary)",
              "secondary-fixed": "#83fba5",
              "on-primary-container": "var(--color-on-primary-container)",
              "surface-dim": "var(--color-surface-dim)",
              "primary": "var(--color-primary)",
              "surface": "var(--color-surface)",
              "on-surface": "var(--color-on-surface)",
              "on-error-container": "var(--color-on-error-container)",
              "surface-container-lowest": "var(--color-background)",
              "on-tertiary-container": "var(--color-on-tertiary-container)",
              "on-error": "var(--color-on-error)",
              "on-primary": "var(--color-on-primary)",
              "primary-fixed-dim": "#f0c12c",
              "on-tertiary": "var(--color-on-tertiary)",
              "secondary-fixed-dim": "#66dd8b",
              "on-secondary-fixed-variant": "#005227",
              "primary-fixed": "#ffdf90",
              "on-tertiary-fixed": "#410005"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "base": "8px",
              "md": "24px",
              "xl": "80px",
              "sm": "12px",
              "container-margin": "24px",
              "xs": "4px",
              "gutter": "16px",
              "lg": "48px"
      },
      "fontFamily": {
              "label-sm": ["Plus Jakarta Sans"],
              "label-md": ["Plus Jakarta Sans"],
              "headline-md": ["Playfair Display"],
              "body-md": ["Plus Jakarta Sans"],
              "headline-lg-mobile": ["Playfair Display"],
              "body-lg": ["Plus Jakarta Sans"],
              "display-lg": ["Playfair Display"],
              "headline-lg": ["Playfair Display"]
      },
      "fontSize": {
              "label-sm": ["12px", {"lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500"}],
              "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.03em", "fontWeight": "600"}],
              "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
              "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "headline-lg-mobile": ["28px", {"lineHeight": "1.2", "fontWeight": "600"}],
              "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
