export const SUPPORTED_CUISINES = [
  'Afghan',
  'African',
  'American',
  'Andhra',
  'Arab',
  'Asian',
  'Assamese',
  'Awadhi',
  'Bengali',
  'Bihari',
  'British',
  'Burmese',
  'Cantonese',
  'Caribbean',
  'Chettinad',
  'Chinese',
  'Coastal Karnataka',
  'Continental',
  'Coorg',
  'Ethiopian', // From original hardcoded list
  'European',
  'French',
  'Fusion',
  'Goan',
  'Greek',
  'Gujarati',
  'Haryana',
  'Himachal',
  'Hunan',
  'Hyderabadi',
  'Indian',
  'Indo Chinese',
  'Indonesian',
  'Italian',
  'Japanese',
  'Jewish',
  'Jharkhand',
  'Karnataka',
  'Kashmiri',
  'Kerala',
  'Kongunadu',
  'Konkan',
  'Korean',
  'Lucknowi',
  'Maharashtrian',
  'Malabar',
  'Malaysian',
  'Malvani',
  'Mangalorean',
  'Mediterranean',
  'Mexican',
  'Middle Eastern',
  'Mughlai',
  'Nagaland',
  'Nepalese',
  'North East India',
  'North Indian',
  'North Karnataka',
  'Oriya',
  'Pakistani',
  'Parsi',
  'Punjabi',
  'Rajasthani',
  'Shandong',
  'Sichuan',
  'Sindhi',
  'South Indian',
  'South Karnataka',
  'Sri Lankan',
  'Tamil Nadu',
  'Thai',
  'Udupi',
  'Uttar Pradesh',
  'Uttarakhand-North Kumaon',
  'Vietnamese'
];

export const CUISINE_ICONS = {
  Italian: 'skillet',
  Thai: 'restaurant',
  Mexican: 'local_pizza',
  Ethiopian: 'ramen_dining',
  Indian: 'curry',
  Japanese: 'sushi',
  French: 'wine_bar',
  Chinese: 'rice_bowl',
  // Default icons for others can be handled in the component
};
