import React from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';

const TermsAndConditions = () => {
  const navigate = useNavigate();

  const sections = [
    {
      title: "1. Acceptance of Terms",
      content: "Welcome to Modern Kitchen (the \"Application\"), an AI-powered culinary coaching service operated by Epicurean AI. By creating an account, subscribing to our services, or using the Application, you agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use the Application."
    },
    {
      title: "2. Eligibility & User Accounts",
      content: "You must be at least 13 years old to use this Application. You agree to provide accurate, current, and complete information during registration. You are solely responsible for safeguarding your password and account credentials. Epicurean AI cannot and will not be liable for any loss or damage arising from your failure to comply with account security."
    },
    {
      title: "3. Subscription Plans & Billing",
      content: "We offer free access (\"Taste Plan\") and premium subscription plans (\"Savor Premium\" and \"Feast Ultimate\"). Subscriptions are billed on a recurring monthly or yearly basis. Payments are processed securely via our integration partners, including Razorpay. By upgrading to a paid plan, you authorize us to charge the applicable subscription fee, plus local taxes (such as GST at 18%), to your selected payment method."
    },
    {
      title: "4. Cancellations & Subscription Changes",
      content: "You may cancel your premium subscription at any time through Account Settings > Billing. Upon cancellation, you will retain access to premium features until the end of your current billing period. Subscription downgrades will take effect at the start of the next billing cycle."
    },
    {
      title: "5. Culinary AI Coach & Content Disclaimer",
      content: "All recipes, meal plans, nutritional advice, and flavor pairings generated by the AI Coach are for informational and inspirational purposes only. Cooking involves inherent risks including heat, knives, and sanitation. You must exercise your own judgment and verify ingredients for food safety, freshness, and personal dietary compliance (especially concerning food allergies and intolerances). We do not guarantee accuracy or safety of user-submitted ingredients or AI-adapted recipes."
    },
    {
      title: "6. User-Generated Content & Family Hub",
      content: "Our Family Kitchen Hub lets you share recipes, grocery lists, and kitchen data with other members. By uploading recipes or notes, you grant Epicurean AI a worldwide, non-exclusive, royalty-free license to host, display, and share that content with your invited members. You agree not to upload any copyrighted or unlawful materials."
    },
    {
      title: "7. Intellectual Property Rights",
      content: "The Application's design, code, logos, branding, and content are protected by copyright, trademark, and intellectual property laws. You are granted a limited, personal, non-transferable license to access the Application for private, non-commercial culinary use. Commercial use of AI-generated content or copying Application layouts is strictly prohibited."
    },
    {
      title: "8. Limitation of Liability",
      content: "To the maximum extent permitted by law, Epicurean AI, its affiliates, and partners shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from: (a) your use of the Application; (b) any culinary mishap, injury, or illness resulting from recipes cooked using our guide; or (c) any unauthorized access to your personal data."
    },
    {
      title: "9. Governing Law & Jurisdiction",
      content: "These Terms shall be governed by and construed in accordance with the laws of India, without regard to its conflict of law principles. Any dispute arising out of or relating to these terms shall be subject to the exclusive jurisdiction of the courts located in Delhi, India."
    },
    {
      title: "10. Contact Us",
      content: "If you have any questions or complaints regarding these Terms and Conditions, please contact our support team at legal@epicurean.ai or visit our Help Center."
    }
  ];

  return (
    <div className="min-h-screen bg-background text-on-surface font-body-md pt-24 pb-32">
      <div className="max-w-4xl mx-auto px-container-margin">
        {/* Navigation Header */}
        <header className="mb-xl flex items-center gap-4">
          <button 
            onClick={() => navigate(-1)}
            className="w-12 h-12 rounded-full bg-surface-container flex items-center justify-center hover:bg-surface-container-highest transition-colors active:scale-95 shadow-sm"
            aria-label="Go Back"
          >
            <span className="material-symbols-outlined text-on-surface">arrow_back</span>
          </button>
          <div>
            <span className="text-label-sm font-label-sm text-primary uppercase tracking-widest">Legal Agreement</span>
            <motion.h1 
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              className="font-display-lg text-display-lg text-on-surface leading-tight"
            >
              Terms & Conditions
            </motion.h1>
          </div>
        </header>

        {/* Intro Alert Box */}
        <div className="bg-surface-container-low border border-primary/10 rounded-3xl p-6 mb-lg flex gap-4 items-start shadow-sm">
          <span className="material-symbols-outlined text-primary !text-3xl mt-0.5" style={{ fontVariationSettings: "'FILL' 1" }}>gavel</span>
          <div>
            <h2 className="font-headline-sm text-on-surface mb-1">Please Read Carefully</h2>
            <p className="text-on-surface-variant font-body-md">
              Last updated: May 21, 2026. By accessing or using Modern Kitchen, you accept these terms. These terms contain important disclaimers regarding food allergies, cooking hazards, and automated recipe safety.
            </p>
          </div>
        </div>

        {/* Main Content Layout */}
        <main className="bg-surface-container rounded-[2.5rem] p-8 md:p-12 border border-outline-variant/30 shadow-sm space-y-8">
          {sections.map((sec, i) => (
            <motion.section 
              key={i}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.05 }}
              className="space-y-3"
            >
              <h3 className="font-headline-md text-headline-md text-primary">{sec.title}</h3>
              <p className="text-on-surface-variant font-body-lg leading-relaxed text-justify">{sec.content}</p>
              {i < sections.length - 1 && <div className="h-px bg-outline-variant/20 pt-4" />}
            </motion.section>
          ))}
        </main>

        <div className="mt-8 text-center text-label-sm text-on-surface-variant/40">
          Epicurean AI Legal Operations • Delhi, India
        </div>
      </div>
    </div>
  );
};

export default TermsAndConditions;
